version: '3.0'
services:
  # Container for ROS2 VLP LiDAR
  vlplidar-ws:
    # Build or Reference the image
    build:
      context: .
      dockerfile: Dockerfile
    image: ros2-vlp-ws
    container_name: ros2-vlp-ws
    stdin_open: true
    tty: true
    privileged: true
    command: bash
    network_mode: host
    working_dir: /home/user/vlplidar_ws

    # Container Settings
    environment:
      - DISPLAY=${DISPLAY}
      # Set ros2 environment variables.
      # References:
      # - https://docs.ros.org/en/humble/Concepts/Intermediate/About-Domain-ID.html
      # - https://docs.ros.org/en/humble/Tutorials/Beginner-CLI-Tools/Configuring-ROS2-Environment.html
      # - https://docs.ros.org/en/humble/Tutorials/Demos/Logging-and-logger-configuration.html#console-output-colorizing
      - ROS_LOCALHOST_ONLY=0
      - ROS_DOMAIN_ID=0
      - ROS2_WS=/home/user/vlplidar_ws
      - RCUTILS_COLORIZED_OUTPUT=1
    volumes:
      # Mount local timezone into container. ( Readonly )
      # Reference: https://stackoverflow.com/questions/57607381/how-do-i-change-timezone-in-a-docker-container
      - /etc/timezone:/etc/timezone:ro
      - /etc/localtime:/etc/localtime:ro
      # Mount X11 server
      - /tmp/.X11-unix:/tmp/.X11-unix
      # Direct Rendering Infrastructure
      - /dev/dri:/dev/dri
      # Mount sound card to prevent Gazebo warning.
      - /dev/snd:/dev/snd
      - /dev/shm:/dev/shm
      # Mount Gazebo models directory to reuse models downloaded during first launch.
      # Reference: https://answers.ros.org/question/365658
      - ./cache/.gazebo:/home/user/.gazebo
      - ../..:/home/user